# AI004 Feature Engineering Pipeline

This notebook demonstrates the feature engineering pipeline for hazard, cyber, temporal, geo, risk, and anomaly data.

The pipeline is designed to be:
- Modular
- Scalable
- Docker-compatible
- ML-ready

In [1]:
#Imports

import pandas as pd

from data_cleaning_pipeline import run_cleaning_pipeline
from feature_engineer import FeatureEngineer

In [2]:
#Sample Dataset

df = pd.DataFrame({
    "timestamp": ["2026-01-01", "2026-01-02", "2026-01-03"],
    "location": ["VIC", "VIC", "NSW"],
    "severity": [3, 5, 8],
    "duration_hours": [2, 4, 6],
    "cyber_incidents": [10, 15, 30]
})
df.head()

    timestamp location  severity  duration_hours  cyber_incidents
0  2026-01-01      VIC         3               2               10
1  2026-01-02      VIC         5               4               15
2  2026-01-03      NSW         8               6               30

In [3]:
#Cleaning

# Empty config uses cleaning defaults
cleaned_df, cleaning_events = run_cleaning_pipeline(df, {})
cleaned_df.head()

    timestamp location  severity  duration_hours  cyber_incidents
0  2026-01-01      VIC         3               2               10
1  2026-01-02      VIC         5               4               15
2  2026-01-03      NSW         8               6               30

In [4]:
#Run Feature Engineering

fe = FeatureEngineer(cleaned_df)
features_df = fe.run()
features_df.head()

2026-04-21 23:52:33,693 - INFO - Running validation checks...
2026-04-21 23:52:33,701 - INFO - Validation passed. Shape: (3, 32)

Data Quality Score: 90.00/100

 PIPELINE COMPLETED SUCCESSFULLY
{'hazard_features': 6, 'cyber_features': 8, 'temporal_features': 6, 'geo_features': 3, 'risk_features': 3, 'anomaly_features': 2}

,timestamp,location,severity,duration_hours,cyber_incidents,disaster_severity_score,event_intensity_index,hazard_normalized,severity_change_rate,hazard_trend_index,...,lag_1,lag_2,time_decay_factor,geo_risk_zone_score,location_encoded,regional_event_count,combined_risk_index,adaptive_risk_index,z_score,outlier_flag
0,2026-01-01,Vic,3,2,10,4.5,6,0.375,0.0,3.000000,...,0.0,0.0,1.000000,0.2,1,2,30,2.727273,-0.800641,0
1,2026-01-02,Vic,5,4,15,7.5,20,0.625,2.0,4.000000,...,10.0,0.0,0.904837,0.5,1,2,75,5.555556,-0.320256,0
2,2026-01-03,Nsw,8,6,30,12.0,48,1.000,3.0,5.333333,...,15.0,10.0,0.818731,1.0,0,1,240,12.413793,1.120897,0

In [5]:
#Feature Groups Summary

mapping = fe.feature_mapping()

for k, v in mapping.items():
    print(f"{k}: {len(v)} features")

In [6]:
#Validation Check

fe.validate()

2026-04-21 23:52:33,778 - INFO - Running validation checks...
2026-04-21 23:52:33,784 - INFO - Validation passed. Shape: (3, 32)

Data Quality Score: 90.00/100

In [7]:
#Output Preview

features_df.head()

,timestamp,location,severity,duration_hours,cyber_incidents,disaster_severity_score,event_intensity_index,hazard_normalized,severity_change_rate,hazard_trend_index,...,lag_1,lag_2,time_decay_factor,geo_risk_zone_score,location_encoded,regional_event_count,combined_risk_index,adaptive_risk_index,z_score,outlier_flag
0,2026-01-01,Vic,3,2,10,4.5,6,0.375,0.0,3.000000,...,0.0,0.0,1.000000,0.2,1,2,30,2.727273,-0.800641,0
1,2026-01-02,Vic,5,4,15,7.5,20,0.625,2.0,4.000000,...,10.0,0.0,0.904837,0.5,1,2,75,5.555556,-0.320256,0
2,2026-01-03,Nsw,8,6,30,12.0,48,1.000,3.0,5.333333,...,15.0,10.0,0.818731,1.0,0,1,240,12.413793,1.120897,0

# Key Observations

- Hazard features capture disaster intensity and volatility.
- Cyber features represent attack patterns and incident spikes.
- Temporal features provide time-series context.
- Geo features encode location-based risk.
- Risk features combine multi-domain signals.
- Anomaly features detect statistical outliers.

This pipeline is designed for real-world ML risk prediction systems.